# Generated by Django 6.0.5 on 2026-06-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('manager', 'Manager'), ('worker', 'Worker')], default='worker', max_length=20),
            preserve_default=False,
        ),
    ]
